### ISSUE TITLE
BoardSituation definition

### ISSUE THREAD

**Issue by jtmcoderscamp** [jtmcoderscamp/chess#12]
Develop a class containing the information about the situation on the board.
The class should:
 - [x] contain information about position on the board and a reference to previous situation
 - [x] have a getter or a normal method that returns the position in the form of an 8x8 array of objects of ChessPiece class or nulls (when nothing stands on a given field)
 - [x] have complex constructor behavior or static methods allowing creation of each of the following:
    - [x] the starting situation (starting chess position with no previous situation)
    - [x] blank board (nothing on the board, no previous situation)
    - [SKIPPED] board with given previous situation and current position (as 8x8 array of the same kind the Situation itself returns in appropriate method)

**Comment by jtmaluszynski** [comment]
Not everything was done, especially regarding creation of situations based on old position/situation - this will need to be addressed later but the foundation has been laid.
